<QuizManager>
    HomeScreen:
        name: "home"

<HomeScreen>
    BoxLayout:
        BoxLayout:
            orientation: "vertical"
            Label:
                size_hint: .2, .2
                text: "Username"
            BoxLayout:
                orientation: "horizontal"
                TextInput:
                    id: two
                    size_hint: .2, .2
                    hint_text: "enter the answer here"